apiVersion: apps/v1
kind: Deployment
metadata:
  name: sevenfood-order-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sevenfood-order-api
  template:
    metadata:
      labels:
        app: sevenfood-order-api
    spec:
      containers:
        - name: sevenfood-order-api-container
          image: rogeriofontes/sevenfood-order-api:latest
          ports:
            - containerPort: 9996
        