version: '3'

services:
  postgres-compose:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Postgres2019!"
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - /opt/postgres/data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres-compose-network

  db-init:
    image: postgres:12
    depends_on:
      - postgres-compose
    entrypoint: ["sh", "-c", "until pg_isready -h postgres-compose -U postgres; do echo 'Waiting for PostgreSQL to start...'; sleep 2; done; psql -h postgres-compose -U postgres -f /docker-entrypoint-initdb.d/init.sql"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Postgres2019!"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres-compose-network

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "infra@sevenfoodorder.com.br"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2019!"
    ports:
      - "16543:80"
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
